=== PabloMartinTomasi/Lenguajes-de-marcas/XML/clase/tienda.dtd
<!ELEMENT tiendas (producto+)>
<!ELEMENT producto (nombre, pvp, descripcion, stock, iva)>
<!ATTLIST producto
          id CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT pvp (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT stock (#PCDATA)>
<!ELEMENT iva (#PCDATA)>

=== PabloMartinTomasi/Lenguajes-de-marcas/XML/clase/tienda.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tiendas SYSTEM "file:/C:/Programacion_H2_1T_Pablo_Martin_Tomasi/Lenguajes-de-marcas/XML/clase/tienda.dtd">
<?xml-stylesheet type="text/xsl" href="file:/C:/Programacion_H2_1T_Pablo_Martin_Tomasi/Lenguajes-de-marcas/XML/clase/tienda.xsl"?>
<tiendas>
  <producto id="1">
    <nombre>Salchichón</nombre>
    <pvp>12</pvp>
    <descripcion>Salchichón iberico de Salamanca</descripcion>
    <stock>20</stock>
    <iva>10</iva>
  </producto>

  <producto id="2">
    <nombre>Pechuga pavo</nombre>
    <pvp>17</pvp>
    <descripcion>Pechuga de pavo al corte</descripcion>
    <stock>30</stock>
    <iva>10</iva>
  </producto>

  <producto id="3">
    <nombre>Jamón Ibérico</nombre>
    <pvp>58</pvp>
    <descripcion>Producto Ibérico 5j</descripcion>
    <stock>7</stock>
    <iva>21</iva>
  </producto>

  <producto id="4">
    <nombre>Queso de Cabra</nombre>
    <pvp>12</pvp>
    <descripcion>Rulo de queso de cabra</descripcion>
    <stock>45</stock>
    <iva>21</iva>
  </producto>

  <producto id="5">
    <nombre>Pan de molde</nombre>
    <pvp>1.25</pvp>
    <descripcion>Pan de molde son corteza</descripcion>
    <stock>22</stock>
    <iva>10</iva>
  </producto>


</tiendas>
